export const VISIBILITY_FILTERS = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_COMPLETED: 'SHOW_COMPLETED',
	SHOW_ACTIVE: 'SHOW_ACTIVE'
};

export const TODO_ADD = 'TODO_ADD';
export const TODO_REMOVE = 'TODO_REMOVE';
export const TODO_TOGGLE = 'TODO_TOGGLE';
export const TODO_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
